"use strict";
exports.__esModule = true;
exports.Input = exports.Button = exports.COLOR = exports.GLOBAL_STYLE = void 0;
var Button_1 = require("./components/atoms/Button");
exports.Button = Button_1["default"];
var Input_1 = require("./components/atoms/Input");
exports.Input = Input_1["default"];
var color_1 = require("./styles/color");
exports.COLOR = color_1["default"];
var global_1 = require("./styles/global");
exports.GLOBAL_STYLE = global_1["default"];
